kafka:
  producer:
    bootstrap-servers: ${KAFKA_URL}
    topic: "btc_weight_average"
    transactional-id: "prod-1"
  consumer:
    bootstrap-servers: ${KAFKA_URL}
    topic: "btc_usd"
    group-id: "my-group"


exchanges-configuration:
  exchanges:
    - name: "hitbtc"
      coefficient: 0.33333333333333333333
    - name: "bitfinex"
      coefficient: 0.33333333333333333333
    - name: "okcoin"
      coefficient: 0.33333333333333333333